## Elección de Base de Datos: MongoDB

**MongoDB fue seleccionado como solución de persistencia principal debido a su óptimo alineamiento con los requisitos específicos del dominio de reconocimiento de señas.** La naturaleza semi-estructurada y variable de los datos generados por el sistema - que incluye landmarks de manos, rutas de videos, metadatos de sesiones y resultados de predicciones en tiempo real - se beneficia significativamente del modelo de documentos flexibles que ofrece MongoDB. A diferencia de las bases relacionales, MongoDB permite almacenar estructuras jerárquicas como las coordenadas de landmarks (arrays numéricos) junto con metadatos descriptivos (etiquetas, rutas de video, tamaños de imagen) en un mismo documento, evitando complejas operaciones de JOIN y manteniendo la integridad contextual de los datos.

**La escalabilidad horizontal de MongoDB resulta crucial para manejar el volumen previsto de operaciones en tiempo real.** Las características de la aplicación - especialmente el componente de WebSockets para predicciones instantáneas - generan patrones de acceso con frecuentes operaciones de escritura y lecturas concurrentes. MongoDB maneja eficientemente estas cargas mediante sharding, distribuyendo los datos a través de múltiples nodos. Esta capacidad es vital considerando los requisitos de rendimiento para procesar streaming de video y predicciones con baja latencia.

**El modelo de datos orientado a documentos se adapta orgánicamente a la evolución del sistema.** En fases de investigación y desarrollo, donde los esquemas de datos pueden cambiar frecuentemente (nuevos metadatos, ajustes en estructuras de landmarks, adición de métricas), MongoDB permite iteraciones rápidas sin costosas migraciones de esquema. Esta flexibilidad es particularmente valiosa en proyectos académicos como este, donde los requisitos pueden refinarse durante el desarrollo.

**Para el almacenamiento de videos y archivos binarios, MongoDB ofrece GridFS como solución integrada.** Aunque las rutas de videos se almacenan inicialmente como referencias, GridFS permite gestionar archivos de gran tamaño que exceden el límite de 16MB por documento, manteniendo la consistencia con los metadatos de sesiones en la misma base de datos. Esto simplifica la arquitectura al evitar sistemas de almacenamiento separados para contenido multimedia.

**Las operaciones de agregación de MongoDB permiten análisis avanzados de los datos de sesiones.** Almacenar predicciones como documentos anidados dentro de sesiones de usuario facilita consultas como: "recuperar todos los gestos con confianza menor al 80% para un usuario específico" o "calcular estadísticas de precisión por sesión". Estas capacidades son esenciales para generar reportes de rendimiento del modelo y análisis de uso sin complejas transformaciones de datos.

**La integración con el stack tecnológico existente es sencilla mediante PyMongo.** La naturaleza JSON de los documentos se alinea con el formato de intercambio de datos en la aplicación Python, reduciendo la sobrecarga de serialización. Esto optimiza el rendimiento en operaciones críticas como el registro de predicciones durante sesiones en tiempo real.

En síntesis, MongoDB proporciona la combinación óptima de flexibilidad, rendimiento y escalabilidad requerida para soportar tanto el componente de investigación (manejo de datasets de landmarks y metadatos variables) como el sistema de producción (gestión de sesiones en tiempo real y almacenamiento de predicciones con videos asociados), asegurando una base sólida para futuras mejoras y expansiones del proyecto.
