// app/layout.tsx
import './css/style.css'
import { Inter, Architects_Daughter } from 'next/font/google'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/context/AuthContext'  // 👈 Importa el provider

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-gray-900 text-gray-200 tracking-tight`}>
        <AuthProvider> {/* 👈 Aquí envolvemos TODA la app */}
          <div className="flex flex-col min-h-screen overflow-hidden">
            <Header />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
